[global]
workers = 2
loglevel = "debug"#"info" # try "info" for interactive test, but use "warn" for service

[[notify]]
# mail notification
id = "mail-someone"
type = "mail"
server = "server.com"
port = 587
user = "sender@server.com"
pass = ""
to = ["receiver@server.com", "r2@server.com"]

[[notify]]
# jabber notifcation
id = "jabber-group1"
type = "jabber"
server = "talk.google.com"
port = 5223
user = "sender@gmail.com"
pass = "pass"
to = ["receiver@gmail.com"]
repeat_fail = ["1m"]

[[notify]]
# notify by notify-send, you need desktop linux for that
id = "cmd-dtnotify"
type = "cmd"
subject_fail = "FAIL"
subject_slow = "SLOW"
subject_fail_ok = "OK"
subject_slow_ok = "OK"
text_fail = "{check}, code: {response_code}"
text_slow = "{check}, time: {response_time}"
text_fail_ok = "{check} working again!"
text_slow_ok = "{check} speed is back!"
cmd = 'notify-send "{subject}" "{text}"'

[[notify]]
id = "cmd-nXrestart"
type = "cmd"
cmd = "ssh root@server echo 'service nginx restart'"
repeat_fail = ["0"] #run once, never repeat
no_recovery = true # do not restart on recovery ;-)


[[check]]
# typical simple web check
id = "web-google"
check = "http://google.com"
fail = 3
redirs = 10
time = 2000
repeat = "10m"

[[check]]
# test JSON api
id = "web-json"
check = "https://jsonplaceholder.typicode.com/posts"
method = "POST"
repeat = "10m"
code = 201 # we should receive "created" answer

[[check]]
# test urlencoded POST api
id = "web-urlenc"
check = "http://api.forismatic.com/api/1.0/"
params = "method=getQuote&format=json&key=1234&lang=en"
method = "POST"
repeat = "10m"
look_for = "quoteText"

[[check]]
# check web with wrong certificate
id = "web-wrongcrt"
type = "insecureweb"
check = "https://self-signed.badssl.com"
repeat = "10m"

[[check]]
# alert if cpu load on remote server is more then 50%, change SERVER to actual name/ip
id = "cmd-cpu50"
type = "cmd"
check = "ssh"
params = "SERVER uptime | awk '{f=$(NF-2); exit (substr(f,1,length(f)-1)>0.5)}'"
repeat = "10s"
time = 10000

[[check]]
# pinging microsoft should fail
id = "ping-microsoft"
type = "ping"
check = "microsoft.com"
repeat = "10m"
notify_fail = ["cmd-dtnotify"] # only mail notification

[[check]]
id = "smtp-google"
type = "port"
check = "smtp.gmail.com:587"
repeat = "10m"
notify_slow = [] #disable slows for this check
